name: CI
on:
    push:
        branches: [main]
    pull_request:
jobs:
    ci:
        name: CI
        runs-on: ubuntu-latest
        permissions:
            contents: read
        timeout-minutes: 5
        steps:
            - name: Checkout code
              uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
            - name: Set up Node.js
              uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
              with:
                  node-version-file: package.json
                  cache: npm
            - name: Set up PHP
              uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # v2
              with:
                  php-version: '8.3'
            - name: Get Composer cache directory
              id: composer-cache
              run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
            - name: Cache Composer packages
              uses: actions/cache@2c8a9bd7457de244a408f35966fab2fb45fda9c8 # v6
              with:
                  path: ${{ steps.composer-cache.outputs.dir }}
                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                  restore-keys: ${{ runner.os }}-composer-
            - name: Install Node dependencies
              run: npm ci
            - name: Install Composer dependencies
              run: composer install
            - name: Build plugin
              run: npm run build
            - name: Lint PHP files
              run: composer lint
            - name: Lint Other files
              run: npm run lint
