name: Verify
on:
    push:
        branches: [main]
    pull_request:
jobs:
    verify:
        name: Verify
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
            - uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4
              with:
                  node-version-file: package.json
            - uses: actions/cache@3624ceb22c1c5a301c8db4169662070a689d9ea8 # v4
              with:
                  path: node_modules
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: ${{ runner.os }}-node-
            - uses: shivammathur/setup-php@c541c155eee45413f5b09a52248675b1a2575231 # v2
            - uses: actions/cache@3624ceb22c1c5a301c8db4169662070a689d9ea8 # v4
              with:
                  path: vendor
                  key: ${{ runner.os }}-vendor-${{ hashFiles('**/composer.lock') }}
                  restore-keys: ${{ runner.os }}-vendor-
            - name: Install Node packages
              run: npm install
            - name: Install Composer packages
              run: composer install
            - name: Lint files
              run: npm run lint
            - name: Lint PHP files
              run: composer lint
